### ISSUE TITLE
Failure with mojave

### ISSUE THREAD

**Issue by jimhester** [r-lib/xml2#235]
Something is wrong with the configure script on majove, the paths returned by xml2-config are either not correct or need to be adjusted to properly link. Likely related to https://github.com/r-lib/xml2/pull/197

**Comment by juanmayorgahenao** [comment]
Having issues installing with Mojave too. Any solutions?

**Comment by scottmmjackson** [comment]
~~It looks like an unusable version of `libxml-2.0` comes with Mojave, and the configure script treats the `xml2-config` on `PATH` as overriding all options (including environment variables).~~ I've discovered this isn't true, but it took me a while to figure it out. See the bottom of this comment.

This is troublesome because it means I cannot then install `libxml2` with `brew` because the configure script will keep looking at Mojave's framework installation of `libxml2` instead.

It looks like moving `xml2-config` out of the way (via directly editing the configure script) doesn't solve this problem either. I've tried running in debug mode and I don't see anything promising from it.

I hacked it a little more to get some debugging info and the error that seems to be thrown is that `stdio.h` isn't found: this sounds like an absence of XCode command line tools that ought to be trapped for by the configure script. 

I went through this: https://stackoverflow.com/questions/51761599/cannot-find-stdio-h

Which suggests this: `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

That fixed the problem. And in fact, after installing that, `xml2` installed just fine from the R console's `install.packages()` function.

**SUMMARY:** If you encounter this error, run `xcode-select --install` and then `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`.
