### ISSUE TITLE
unable to iterate read_html over 20 iterations

### ISSUE THREAD

**Issue by Sbirch556** [r-lib/xml2#259]
I'm having an issue using xml2's read_html function over 20 iterations in a for loop or applied over 20 iterations in an apply function. There is additional code provided to fetch the URL, but the issue is with read_html, I'm given the error.

Error: 'NA' does not exist in current working directory. 

My debugger opens up a check_path, it appears that during the 20th iteration an NA is returned and a stop is called. Very lost on what the issue is because if the length of my data < 20 the code has no problem running.

The Function to Read the Data
```r
library(httr)
library(XML)
library(magrittr)
library(xml2)

working <- function(url_old){
  
ctnt <- httr::GET(url_old) %>% 
  content("text", encoding="UTF8") 
tbls <- XML::readHTMLTable(ctnt, stringsAsFactors = FALSE)   
tbls <- tbls[names(tbls)!="NULL"]
names(tbls) <- xml2::read_html(gsub("<!--[if gte mso 9]>", "", ctnt, fixed=TRUE)) %>%
  xml2::xml_find_all(".//name") %>%
  xml2::xml_text()

return(tbls)

}

data_set <- lapply(some_urls, working)
```

Some Data
```r

```

**Comment by jimhester** [comment]
I am not sure what the issue is, there is no data attached here, but I would guess it is due to rate limiting or an invalid URL in the 20th url rather than an issue with this package. We can re-open this if you are able to provide a reproducible example of your issue.

If you continue to have issues you may want to open it at <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
