### ISSUE TITLE
FR: connection to xml object?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xml2#323]
I've got a page with a node whose `text()` contains a large (`nchar(xml_text(node))` is ~ 600K) JSON object with data I'd like to parse as JSON.

I'd like to avoid passing this through R's string cache if possible -- the first option that comes to mind is to get a connection to that text (basically a pointer, maybe a `textConnection`?) and then pass it to `jsonlite::stream_in`. I might be wrong about whether this will actually achieve what I want.

Does that sound feasible? I don't know the internals of either package well enough.

**Comment by jimhester** [comment]
Basically R packages cannot create custom connections due to CRANs regulations, curl was grandfathered in.

If xml2 allowed you to convert nodes to raw objects that would avoid the string cache and you could then pass it io `jsonlite::toJSON()`.

But maybe a better solution would be to use a non-R external script to filter your xml2 file for just the node you are looking for using `pipe()` and pass that connection directly to `jsonlite::stream_in()`.

**Comment by MichaelChirico** [comment]
I see... another workaround could be if write_xml doesn't materialize the
object to R, would that work?

**Comment by jimhester** [comment]
Maybe, but 600k is not very big, I doubt the overhead is very high.

**Comment by MichaelChirico** [comment]
I have a feeling I'm hitting an rstudio bug -- loading it to R (or perhaps
it's printing it in console) completely chokes the session to the point I
have to restart rstudio (not just the R session), hence looking for a
workaround

**Comment by jimhester** [comment]
It could be something related to the environment pane? Do you see the same behavior if you run R outside of RStudio?

**Comment by MichaelChirico** [comment]
Usually not. but let me file this on the rstudio tracker of I can reproduce
it, it's not related to xml2 specifically.
