### ISSUE TITLE
Error with kableExtra::column_spec() might involve xml2

### ISSUE THREAD

**Issue by eipi10** [r-lib/xml2#328]
A recent [question on StackOverflow](https://stackoverflow.com/questions/65419443/kableextra-column-spec-error-maybe-dplyr-summarise) describes the following error:

```
library(tidyverse)
library(knitr)
library(kableExtra)

Summary <- mtcars %>% 
            group_by(cyl, gear, carb) %>% 
            summarise(count = n(), .groups = "keep") %>% 
            arrange(desc(cyl))

kable(Summary, caption = "mtcars Data Summary\n", align = c('l','l','c','c')) %>%
                  kable_styling(bootstrap_options = c("striped","hover"),full_width = FALSE, position = "left") %>% 
                  collapse_rows(columns = 1, valign = "top") %>% 
                  column_spec(1, width = "3cm") %>% 
                  column_spec(2, width = "3cm") %>% 
                  column_spec(3, width = "2cm") %>% 
                  column_spec(4, width = "2cm")

# Error in xml_children(x)[[search]] : subscript out of bounds
```
The code works as expected until the last `column_spec` call, which produces the error. There's also an unsolved [`kableExtra` issue](https://github.com/haozhu233/kableExtra/issues/513) that seems to be similar to this and that may be [related to the `xml2` package](https://github.com/haozhu233/kableExtra/issues/513#issuecomment-704011589).

I thought I would report these errors here in case this is a bug in the `xml2` package. If not, do you have any ideas on what's going wrong and whether there might be a workaround?

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by eipi10** [comment]
I think you can close this. The error occurred with the listed code back in December 2020 when I reported this. However, it no longer occurs with the current version of `kableExtra`.
