### ISSUE TITLE
xml_set_attrs removes namespace

### ISSUE THREAD

**Issue by JHLasbatre** [r-lib/xml2#345]
Hi team

I'm using xml2::xml_set_attrs to modify an xml us the following

```r
# read xml from some file
xmlparent <- read_xml(XML_Input_Template_Path)

# find a specific path and add attributes to elements
xmlparent %>% xml_find_all(., xpath = ".//d1:command[@fragment='paramModelDate']/r:paramInstance") %>%
    xml_set_attrs(., c("xsi:type" = "FdbModelDate", "date" = as.character(as.Date(FDBDate, format = "%Y%m%d")), "model" = FDBModel, "repository" = FDB_Path))
```

Initialy my xml was lilke this:

<command issue="set" fragment="paramModelDate" >
		<paramInstance xmlns="http://www.apt.com/reporting" xsi:type="FdbModelDate" model="WorldLocal(USD)" date="2021-06-16" repository="C:\FCI\FDB\FDBRepoFolder" />
	</command>

After using xml_set_attrs the attributes are correctly modified but the namespace had been removed. How can I force it here ?

<command issue="set" fragment="paramModelDate">
		<paramInstance xsi:type="FdbModelDate" model="EuropeLocal(EUR)" date="2021-05-12" repository="C:/FCI/FDB/FDBRepoFolder"/>
	</command>

Thanks

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
