### ISSUE TITLE
passsing variable to  conditional xpath expression  returns null whereas passing value gives result

### ISSUE THREAD

**Issue by iamihgam** [r-lib/xml2#372]
I have a variable say x which can take any integer value.

When I try to pass the value directly (say, x=0) instead of variable  as below, I get respective nodes

```
root_unitgroup %>% xml_find_all("//*[@dataSetInternalID = '0']")
```
however, if I pass variable as below , I  get empty node, or null value if I use xml_find_first instead .

```
root_unitgroup %>%  xml_find_all("//*[@dataSetInternalID = '$x']")
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
