### ISSUE TITLE
as_list ignore elements when there are element duplicates

### ISSUE THREAD

**Issue by porfila** [r-lib/xml2#381]
Please check attached xml. Element such are "EnteteFacture" etc does not apper on the list (as there are multiple "LigneFacture"
[dupicateLine..txt](https://github.com/r-lib/xml2/files/10529540/dupicateLine.txt)

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
